apiVersion: v1
kind: PersistentVolume
metadata:
  name: gez-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: gez-disk1
    fsType: ext4
